openapi: 3.0.1
info:
  title: aasf-website-backend
  description: Backend for AASF Website
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: Users
    description: Operations related to users
  - name: Specification
    description: The swagger API specification

paths:
  /users/login:
    post:
      tags:
        - Users
      servers:
        - url: /
      description: Log a user in
      requestBody:
        description: Roll number and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
        required: true
      responses:
        200:
          description: Return token and success message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        400:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Invalid Password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Could not login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/changepassword:
    post:
      tags:
        - Users
      servers:
        - url: /
      description: Change user's password
      security:
        - Bearer: []
      requestBody:
        description: Current Password and New Password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordBody'
        required: true
      responses:
        200:
          description: Return success message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /spec:
    get:
      servers:
        - url: /
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Provide a valid JWT token

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
      additionalProperties: true

    MessageResponse:
      type: object
      properties:
        message:
          type: string

    LoginBody:
      required:
        - roll
        - password
      type: object
      properties:
        roll:
          type: string
          example: 2018BCS-000
        password:
          type: string
          example: yourPassword

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: ey.......9X
        message:
          type: string
          example: Successfully Logged in!

    ChangePasswordBody:
      type: object
      required:
        - currentPassword
        - newPassword
      properties:
        currentPassword:
          type: string
          example: yourCurrentPassword
        newPassword:
          type: string
          example: yourNewPassword
